version: '3.8'
services:
  app:
    container_name: mutants-api
    image: mutants-api
    build: ./
    ports:
      - "8080:8080"
    restart: always
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    #links: mutants-api
